/**
 * Creates a comprehensive mock for @sap-ux/project-access that provides all named exports.
 * This prevents ESM "does not provide an export named" errors from transitive consumers.
 */
import { jest } from '@jest/globals';

const stub = jest.fn();

export function createProjectAccessMock(overrides: Record<string, unknown> = {}): Record<string, unknown> {
    return {
        // Constants
        FileName: {
            AdaptationConfig: 'config.json',
            CapJavaApplicationYaml: 'application.yaml',
            ExtConfigJson: '.extconfig.json',
            IndexCds: 'index.cds',
            Library: '.library',
            Manifest: 'manifest.json',
            ManifestAppDescrVar: 'manifest.appdescr_variant',
            MtaYaml: 'mta.yaml',
            Package: 'package.json',
            Pom: 'pom.xml',
            SpecificationDistTags: 'specification-dist-tags.json',
            ServiceCds: 'services.cds',
            Tsconfig: 'tsconfig.json',
            Ui5Yaml: 'ui5.yaml',
            Ui5LocalYaml: 'ui5-local.yaml',
            Ui5MockYaml: 'ui5-mock.yaml',
            UI5DeployYaml: 'ui5-deploy.yaml',
            PackageLock: 'package-lock.json',
            XSAppJson: 'xs-app.json',
            XSSecurityJson: 'xs-security.json',
            DotGitIgnore: '.gitignore',
            MtaExtYaml: 'mta-ext.mtaext'
        },
        DirName: { Changes: 'changes', Webapp: 'webapp' },
        FioriToolsSettings: {},
        MinCdsPluginUi5Version: '0.0.1',
        MinCdsVersion: '0.0.1',
        fioriToolsDirectory: '.fiori',
        // Functions
        getFilePaths: stub,
        normalizePath: stub,
        addPackageDevDependency: stub,
        clearCdsModuleCache: stub,
        createApplicationAccess: stub,
        createProjectAccess: stub,
        deleteCapApp: stub,
        filterDataSourcesByType: stub,
        findAllApps: stub,
        findCapProjectRoot: stub,
        findCapProjects: stub,
        findFioriArtifacts: stub,
        findProjectRoot: stub,
        findRootsForPath: stub,
        getAllUi5YamlFileNames: stub,
        getAppRootFromWebappPath: stub,
        getAppProgrammingLanguage: stub,
        getAppType: stub,
        getCapCustomPaths: stub,
        getCapEnvironment: stub,
        getCapModelAndServices: stub,
        getCapServiceName: stub,
        getCapProjectType: stub,
        getCdsFiles: stub,
        getCdsRoots: stub,
        getCdsServices: stub,
        getCapI18nFolderNames: stub,
        getSpecification: stub,
        getSpecificationModuleFromCache: stub,
        getSpecificationPath: stub,
        getI18nPropertiesPaths: stub,
        getI18nBundles: stub,
        getMinUI5VersionFromManifest: stub,
        getMinUI5VersionAsArray: stub,
        getMinimumUI5Version: stub,
        getMtaPath: stub,
        getMockServerConfig: stub,
        getMockDataPath: stub,
        getNodeModulesPath: stub,
        getPathMappings: stub,
        getProject: stub,
        getProjectType: stub,
        getWebappPath: stub,
        hasUI5CliV3: stub,
        isCapProject: stub,
        isCapJavaProject: stub,
        isCapNodeJsProject: stub,
        loadModuleFromProject: stub,
        readCapServiceMetadataEdmx: stub,
        readUi5Yaml: stub,
        refreshSpecificationDistTags: stub,
        toReferenceUri: stub,
        updatePackageScript: stub,
        getWorkspaceInfo: stub,
        hasMinCdsVersion: stub,
        checkCdsUi5PluginEnabled: stub,
        readFlexChanges: stub,
        processServices: stub,
        getMainService: stub,
        getGlobalCdsHomePath: stub,
        execNpmCommand: stub,
        findRecursiveHierarchyKey: stub,
        getTableCapabilitiesByEntitySet: stub,
        hasDependency: stub,
        // Apply overrides last
        ...overrides
    };
}
