export const SYSTEMS_EVENT = 'SYSTEM_DETAILS_VIEW_EVENT';

export enum SystemAction {
    VIEW_LAUNCHED = 'VIEW_LAUNCHED',
    TEST_CONNECTION = 'TEST_CONNECTION',
    SYSTEM = 'SYSTEM',
    GUIDED_ANSWERS = 'GUIDED_ANSWERS'
}

export enum SystemActionStatus {
    CREATED_SUCCESS = 'CREATED_SUCCESS',
    CREATED_FAIL = 'CREATED_FAIL',
    DELETED_SUCCESS = 'DELETED_SUCCESS',
    DELETED_FAIL = 'DELETED_FAIL',
    UPDATED_SUCCESS = 'UPDATED_SUCCESS',
    UPDATED_FAIL = 'UPDATED_FAIL',
    IMPORT_SUCCESS = 'IMPORT_SUCCESS',
    IMPORT_FAIL = 'IMPORT_FAIL',
    EXPORT_SUCCESS = 'EXPORT_SUCCESS',
    EXPORT_FAIL = 'EXPORT_FAIL',
    LAUNCH_FIORI_GEN_SUCCESS = 'LAUNCH_FIORI_GEN_SUCCESS',
    LAUNCH_FIORI_GEN_FAIL = 'LAUNCH_FIORI_GEN_FAIL'
}

export enum LaunchViewStatus {
    SUCCEED = 'SUCCEED',
    FAILED = 'FAILED'
}

export enum TestConnectionStatus {
    STARTED = 'STARTED',
    SUCCEED = 'SUCCEED',
    FAILED = 'FAILED'
}

export enum GuidedAnswersLinkAction {
    LINK_CREATED = 'LINK_CREATED',
    LINK_CLICKED = 'LINK_CLICKED'
}
