/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("BookingObjectPageObjectPage journey");

        opaTest("Navigate to BookingObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheTravelListGenerated.onFilterBar().iExecuteSearch();

            Then.onTheTravelListGenerated.onTable().iCheckRows();
            When.onTheTravelListGenerated.onTable().iPressRow(0);

            Then.onTheTravelObjectPageGenerated.iSeeThisPage();
            Then.onTheTravelObjectPageGenerated.onTable({ property: "_Booking" }).iCheckRows();
            When.onTheTravelObjectPageGenerated.onTable({ property: "_Booking" }).iPressRow(0);

            Then.onTheBookingObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheBookingObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheBookingObjectPageGenerated.iPressSectionIconTabFilterButton("Booking");
            Then.onTheBookingObjectPageGenerated.iCheckSection({ section: "Booking" });
            Then.onTheBookingObjectPageGenerated.onForm({ section: "Booking" }).iCheckField({ property: "BookingID" });
            Then.onTheBookingObjectPageGenerated.onForm({ section: "Booking" }).iCheckField({ property: "BookingDate" });
            Then.onTheBookingObjectPageGenerated.onForm({ section: "Booking" }).iCheckField({ property: "CustomerID" });
            Then.onTheBookingObjectPageGenerated.onForm({ section: "Booking" }).iCheckField({ property: "AirlineID" });
            Then.onTheBookingObjectPageGenerated.onForm({ section: "Booking" }).iCheckField({ property: "ConnectionID" });
            Then.onTheBookingObjectPageGenerated.onForm({ section: "Booking" }).iCheckField({ property: "FlightDate" });
            Then.onTheBookingObjectPageGenerated.onForm({ section: "Booking" }).iCheckField({ property: "FlightPrice" });
            Then.onTheBookingObjectPageGenerated.onForm({ section: "Booking" }).iCheckField({ property: "DestinationRisk" });
            When.onTheBookingObjectPageGenerated.iPressSectionIconTabFilterButton("BookingSupplement");
            Then.onTheBookingObjectPageGenerated.iCheckSection({ section: "BookingSupplement" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});