/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom pages:                                       ║ *
 * ║   - Create a new page file in this directory.                         ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the JourneyRunner.                            ║ *
 * ║   - Custom page files are not overwritten.                            ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define(['sap/fe/test/ObjectPage'], function(ObjectPage) {
    'use strict';

    const CustomPageDefinitions = {
        actions: {},
        assertions: {}
    };

    return new ObjectPage(
        {
            appId: '<%- appID %>',
            componentId: '<%- componentID %>',<% if (locals.contextPath) { %>
            contextPath: '<%- contextPath %>'<% } else if (locals.entitySet) { %>
            entitySet: '<%- entitySet %>'<% } %>
        },
        CustomPageDefinitions
    );
});