packages:
  - 'packages/lib/**'
  - 'packages/templates/**'
  - '!packages/templates/**/templates/**'
  - '!packages/templates/**/test-output/**' # Ignoring templates folder within template packages that might contain invalid json characters
