packages:
    - 'packages/**'
    - 'test/*/**'
    - '!packages/**/templates/**'
    - '!packages/**/test-input/**'
    - '!packages/**/test-output/**' # Ignoring templates folder within template packages that might contain invalid json characters
