/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom pages:                                       ║ *
 * ║   - Create a new page file in this directory.                         ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the JourneyRunner.                            ║ *
 * ║   - Custom page files are not overwritten.                            ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

import type Opa5 from "sap/ui/test/Opa5";
import Press from "sap/ui/test/actions/Press";

export const actions = {
    iPressSectionIconTabFilterButton(this: Opa5, section: string) {
        return this.waitFor({
            id: new RegExp(`.*--fe::FacetSection::${section}-anchor$`),
            actions: new Press()
        });
    }
};

export const assertions = {};

export default class ObjectPage {
    actions = actions;
    assertions = assertions;
}
