/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("TravelListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheTravelList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheTravelList.onFilterBar().iCheckFilterField("TravelID");
            Then.onTheTravelList.onFilterBar().iCheckFilterField("AgencyID");
            Then.onTheTravelList.onFilterBar().iCheckFilterField("Kunden ID");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheTravelList.onTable().iCheckCreate({ visible: true });
            // Then.ontheTravelList.onTable().iPressCreate();
            // Then.ontheTravelList.onTable().iPressDelete();
            Then.onTheTravelList.onTable().iCheckDelete({ visible: true });
            // Then.onTheTravelList.onTable().iPressAction("Create Draft");
            Then.onTheTravelList.onTable().iCheckAction("Create Draft", { enabled: true });
            // Then.onTheTravelList.onTable().iPressAction("Check Travel");
            Then.onTheTravelList.onTable().iCheckAction("Check Travel", { enabled: false });
            // Then.onTheTravelList.onTable().iPressAction("Template Draft");
            Then.onTheTravelList.onTable().iCheckAction("Template Draft", { enabled: true });
            // Then.onTheTravelList.onTable().iPressAction("Template Active");
            Then.onTheTravelList.onTable().iCheckAction("Template Active", { enabled: true });
            // Then.onTheTravelList.onTable().iPressAction("Deduct Discount");
            Then.onTheTravelList.onTable().iCheckAction("Deduct Discount", { enabled: false });
            // Then.onTheTravelList.onTable().iPressAction("Set To New");
            Then.onTheTravelList.onTable().iCheckAction("Set To New", { enabled: false });
            // Then.onTheTravelList.onTable().iPressAction("Set To Booked");
            Then.onTheTravelList.onTable().iCheckAction("Set To Booked", { enabled: false });
            Then.onTheTravelList.onTable().iCheckColumns(8, {"TravelID":{"header":"TravelID"},"AgencyID":{"header":"AgencyID"},"CustomerID":{"header":"Kunden ID"},"BeginDate":{"header":"BeginDate"},"EndDate":{"header":"EndDate"},"TotalPrice":{"header":"TotalPrice"},"Memo":{"header":"Memo"},"Status":{"header":"Status"}});

        });


        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheTravelList.onFilterBar().iExecuteSearch();
            
            Then.onTheTravelList.onTable().iCheckRows();

            When.onTheTravelList.onTable().iPressRow(0);
            Then.onTheTravelObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});