/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   Do not edit this file directly. Any changes will be lost.           ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

import type Opa5 from "sap/ui/test/Opa5";
import type { actions as ListReportActions, assertions as ListReportAssertions } from "sap/fe/test/ListReport";
import type { actions as ObjectPageActions, assertions as ObjectPageAssertions } from "sap/fe/test/ObjectPage";
import type { actions as TemplatePageActions, assertions as TemplatePageAssertions } from "sap/fe/test/TemplatePage";
import type Shell from "sap/fe/test/Shell";
import type BaseArrangements from "sap/fe/test/BaseArrangements";
import type { actions as BooksListGeneratedCustomActions, assertions as BooksListGeneratedCustomAssertions } from "../pages/BooksList.gen";
import type { actions as BooksObjectPageGeneratedCustomActions, assertions as BooksObjectPageGeneratedCustomAssertions } from "../pages/BooksObjectPage.gen";

export type Given = Opa5 & BaseArrangements & {
    iTearDownMyApp: () => Given;
    iStartMyApp: (sAppHash?: string, mInUrlParameters?: object) => Given;
    and: Given;
};

export type When = Opa5 & BaseArrangements & {
    onTheBooksListGenerated: Opa5 & ListReportActions & TemplatePageActions & typeof BooksListGeneratedCustomActions;
    onTheBooksObjectPageGenerated: Opa5 & ObjectPageActions & TemplatePageActions & typeof BooksObjectPageGeneratedCustomActions;
    onTheShell: Shell;
};

export type Then = Opa5 & BaseArrangements & {
    onTheBooksListGenerated: Opa5 & ListReportAssertions & TemplatePageAssertions & typeof BooksListGeneratedCustomAssertions;
    onTheBooksObjectPageGenerated: Opa5 & ObjectPageAssertions & TemplatePageAssertions & typeof BooksObjectPageGeneratedCustomAssertions;
    onTheShell: Shell;
};
