/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("TravelObjectPageObjectPage journey");

        opaTest("Navigate to TravelObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            Then.onTheTravelListGenerated.onTable().iCheckRows();
            When.onTheTravelListGenerated.onTable().iPressRow(0);

            Then.onTheTravelObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Check header actions of the Object Page", function (Given, When, Then) {
            // Ensure the opened entity is not in Draft state before uncommenting
            // Then.onTheTravelObjectPageGenerated.onHeader().iCheckEdit({ visible: true });
            // When.onTheTravelObjectPageGenerated.onHeader().iPressEdit();
            Then.onTheTravelObjectPageGenerated.onHeader().iCheckAction({ service: "com.sap.gateway.srvd.dmo.sd_travel_mduu.v0001", action: "setCancellationDateToTomorrow", unbound: false } /* , { enabled: true } */);
            // When.onTheTravelObjectPageGenerated.onHeader().iPressAction({ service: "com.sap.gateway.srvd.dmo.sd_travel_mduu.v0001", action: "setCancellationDateToTomorrow", unbound: false });
            Then.onTheTravelObjectPageGenerated.onHeader().iCheckAction({ service: "com.sap.gateway.srvd.dmo.sd_travel_mduu.v0001", action: "setToBooked", unbound: false } /* , { enabled: true } */);
            // When.onTheTravelObjectPageGenerated.onHeader().iPressAction({ service: "com.sap.gateway.srvd.dmo.sd_travel_mduu.v0001", action: "setToBooked", unbound: false });
            Then.onTheTravelObjectPageGenerated.onHeader().iCheckAction({ service: "com.sap.gateway.srvd.dmo.sd_travel_mduu.v0001", action: "setToNew", unbound: false } /* , { enabled: true } */);
            // When.onTheTravelObjectPageGenerated.onHeader().iPressAction({ service: "com.sap.gateway.srvd.dmo.sd_travel_mduu.v0001", action: "setToNew", unbound: false });
            Then.onTheTravelObjectPageGenerated.onHeader().iCheckAction({ service: "com.sap.gateway.srvd.dmo.sd_travel_mduu.v0001", action: "Check", unbound: false } /* , { enabled: true } */);
            // When.onTheTravelObjectPageGenerated.onHeader().iPressAction({ service: "com.sap.gateway.srvd.dmo.sd_travel_mduu.v0001", action: "Check", unbound: false });
            Then.onTheTravelObjectPageGenerated.onHeader().iCheckAction({ service: "com.sap.gateway.srvd.dmo.sd_travel_mduu.v0001", action: "deductDiscount", unbound: false } /* , { enabled: true } */);
            // When.onTheTravelObjectPageGenerated.onHeader().iPressAction({ service: "com.sap.gateway.srvd.dmo.sd_travel_mduu.v0001", action: "deductDiscount", unbound: false });
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheTravelObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheTravelObjectPageGenerated.iPressSectionIconTabFilterButton("Travel");
            Then.onTheTravelObjectPageGenerated.iCheckSection({ section: "Travel" });
            Then.onTheTravelObjectPageGenerated.onForm({ section: "Travel" }).iCheckField({ property: "TravelID" });
            Then.onTheTravelObjectPageGenerated.onForm({ section: "Travel" }).iCheckField({ property: "AgencyID" });
            Then.onTheTravelObjectPageGenerated.onForm({ section: "Travel" }).iCheckField({ property: "CustomerID" });
            Then.onTheTravelObjectPageGenerated.onForm({ section: "Travel" }).iCheckField({ property: "BeginDate" });
            Then.onTheTravelObjectPageGenerated.onForm({ section: "Travel" }).iCheckField({ property: "EndDate" });
            Then.onTheTravelObjectPageGenerated.onForm({ section: "Travel" }).iCheckField({ property: "BookingFee" });
            Then.onTheTravelObjectPageGenerated.onForm({ section: "Travel" }).iCheckField({ property: "TotalPrice" });
            Then.onTheTravelObjectPageGenerated.onForm({ section: "Travel" }).iCheckField({ property: "LatestCancellationDate" });
            Then.onTheTravelObjectPageGenerated.onForm({ section: "Travel" }).iCheckField({ property: "Memo" });
            Then.onTheTravelObjectPageGenerated.onForm({ section: "Travel" }).iCheckField({ property: "Status" });
            When.onTheTravelObjectPageGenerated.iPressSectionIconTabFilterButton("Booking");
            Then.onTheTravelObjectPageGenerated.iCheckSection({ section: "Booking" });
            Then.onTheTravelObjectPageGenerated.onTable({ property: "_Booking" }).iCheckColumns(undefined, {"BookingID":{"header":"Booking Number"},"BookingDate":{"header":"Booking Date"},"CustomerID":{"header":"Customer ID"},"AirlineID":{"header":"Airline ID"},"ConnectionID":{"header":"Flight Number"},"FlightDate":{"header":"Flight Date"},"FlightPrice":{"header":"Flight Price"},"DestinationRisk":{"header":"Destination Risk"}});
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});