/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and can     ║ *
 * ║   be OVERWRITTEN when you run the OPA test generator again.           ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║      → Create a NEW Journey test file in this directory               ║ *
 * ║      → Follow the same pattern as this file                           ║ *
 * ║      → Add file to opaTests.qunit.js config                           ║ *
 * ║      → Your custom Journey files will NOT be overwritten              ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("FPM journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();
            <%_ startPages.forEach(function(pageName) { %>
            Then.onThe<%- pageName %>.iSeeThisPage();
            <%_ if (filterBarItems && filterBarItems.length > 0) { -%>
                <%_ filterBarItems.forEach(function(item) { _%>
            Then.onThe<%- pageName%>.onFilterBar().iCheckFilterField("<%- item %>");
                <%_ }); -%>
            <%_ } -%>
            <%_ if (tableColumns && Object.keys(tableColumns).length > 0) { _%>
            Then.onThe<%- pageName %>.onTable().iCheckColumns(<%- Object.keys(tableColumns).length %>, <%- JSON.stringify(tableColumns) %>);
            <%_ } %>
            <%_ }); -%>
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});