/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

import opaTest from "sap/ui/test/opaQunit";
import type { Given, When, Then } from "./types/OpaJourneyTypes";
<%_
const usesFilterFieldIdentifier =
    (!hideFilterBar && filterBarItems && filterBarItems.length > 0) ||
    (semanticKey && semanticKey.missingFromFilterBar && semanticKey.missingFromFilterBar.length > 0);
-%>
<% if (usesFilterFieldIdentifier) { -%>
import type { FilterFieldIdentifier } from "sap/fe/test/api/FilterBarAPI";
<% } -%>
import runner from "./pages/JourneyRunner";

function journey() {
    QUnit.module("<%- name%>ListReport journey");

    opaTest("Start application", function (Given: Given, _When: When, Then: Then) {
        Given.iStartMyApp();
        <%_ startPages.forEach(function(pageName) { %>
        Then.onThe<%- pageName %>Generated.iSeeThisPage();
        <%_ }); -%>
    });

    <%_ if (!hideFilterBar && filterBarItems && filterBarItems.length > 0) { -%>
    opaTest("Check filter bar", function (_Given: Given, _When: When, Then: Then) {
        <%_ filterBarItems.forEach(function(item) { _%>
        Then.onThe<%- startLR%>Generated.onFilterBar().iCheckFilterField("<%- item %>" as unknown as FilterFieldIdentifier);
        <%_ }); -%>
    });
<%_ } -%>
<%_ if (semanticKey && semanticKey.missingFromFilterBar && semanticKey.missingFromFilterBar.length > 0) { %>
    opaTest("Add semantic key properties to filter bar", function (_Given: Given, When: When, Then: Then) {
        Then.onThe<%- startLR%>Generated.onFilterBar().iOpenFilterAdaptation();
        <%_ semanticKey.missingFromFilterBar.forEach(function(property) { _%>
        When.onThe<%- startLR%>Generated.onFilterBar().iAddAdaptationFilterField("<%- property %>");
        <%_ }); -%>
        Then.onThe<%- startLR%>Generated.onFilterBar().iConfirmFilterAdaptation();
        <%_ semanticKey.missingFromFilterBar.forEach(function(property) { _%>
        Then.onThe<%- startLR%>Generated.onFilterBar().iCheckFilterField("<%- property %>" as unknown as FilterFieldIdentifier);
        <%_ }); -%>
        <%_ semanticKey.missingFromFilterBar.forEach(function(property) { _%>
        // Then.onThe<%- startLR%>Generated.onFilterBar().iChangeFilterField({ property: "<%- property %>" });
        <%_ }); -%>
        // Then.onThe<%- startLR%>Generated.onFilterBar().iExecuteSearch();
        // Then.onThe<%- startLR%>Generated.onTable("").iCheckRows();
        // Then.onThe<%- startLR%>Generated.onTable("").iSelectRows(0);
        // Then.onThe<%- startLR%>Generated.onTable("").iCheckAction("<Action Name>", { enabled: true });
    });
<%_ } -%>

    // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
    // opaTest("Perform a global search and check the result", function (Given: Given, When: When, Then: Then) {
    //     When.onThe<%- startLR%>Generated.onFilterBar().iChangeSearchField("Search Term");
    //     When.onThe<%- startLR%>Generated.onFilterBar().iExecuteSearch();
    //     Then.onThe<%- startLR%>Generated.onTable("").iCheckRows();
    // });

<%_ if ((toolBarActions && toolBarActions.length > 0 ) || (tableColumns && Object.keys(tableColumns).length > 0)) { -%>
    opaTest("Check table columns and actions", function (_Given: Given, _When: When, Then: Then) {
        <%_ if (toolBarActions && toolBarActions.length > 0) { -%>
        <%_ if (createButton.visible && !isALP) { _%>
        Then.onThe<%- startLR%>Generated.onTable("").iCheckCreate({ visible: true });
        // Then.onthe<%- startLR%>Generated.onTable("").iPressCreate();
        <%_ } _%>
        <%_ if (deleteButton.visible) { _%>
        // Then.onthe<%- startLR%>Generated.onTable("").iPressDelete();
        Then.onThe<%- startLR%>Generated.onTable("").iCheckDelete({ visible: true });
        <%_ } _%>
        <%_ toolBarActions.forEach(function(item) { _%>
        <%_ if (item.visible) { _%>
        // Then.onThe<%- startLR%>Generated.onTable("").iPressAction("<%- item.label %>");
        Then.onThe<%- startLR%>Generated.onTable("").iCheckAction("<%- item.label %>", { enabled: <%- item.enabled === true %> });
        <%_ } _%>
        <%_ }); -%>
        <%_ } -%>
        <%_ if (tableColumns && Object.keys(tableColumns).length > 0) { -%>
        Then.onThe<%- startLR %>Generated.onTable("").iCheckColumns(undefined, <%- JSON.stringify(tableColumns) %>);
        <%_ } %>
    });
<%_ } %>

<% if (startLR) { %>
    opaTest("Navigate to ObjectPage", function (_Given: Given, When: When, Then: Then) {
        // Note: this test will fail if the ListReport page doesn't show any data
        <% if (!hideFilterBar) { %>
        When.onThe<%- startLR%>Generated.onFilterBar().iExecuteSearch();
        <%} %>
        Then.onThe<%- startLR%>Generated.onTable("").iCheckRows();
<% if (navigatedOP) { %>
        When.onThe<%- startLR%>Generated.onTable("").iPressRow(0);
        Then.onThe<%- navigatedOP%>Generated.iSeeThisPage();
<%} %>
    });
<%} %>
    opaTest("Teardown", function (Given: Given) {
        // Cleanup
        Given.iTearDownMyApp();
    });
}

runner.run([journey]);
