/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

import opaTest from "sap/ui/test/opaQunit";
import type { Given, When, Then } from "./types/OpaJourneyTypes";
<%_
const usesFilterFieldIdentifier =
    !hideFilterBar && filterBarItems && filterBarItems.some(function(item) { return item.custom; });
-%>
<% if (usesFilterFieldIdentifier) { -%>
import type { FilterFieldIdentifier } from "sap/fe/test/api/FilterBarAPI";
<% } -%>
import runner from "./pages/JourneyRunner";

function journey() {
    QUnit.module("<%- name%>ListReport journey");

    const defaultTableId = <%- tableIdentifiers && tableIdentifiers.length > 0 ? '"' + tableIdentifiers[0] + '"' : '""' %>;

    opaTest("Start application", function (Given: Given, _When: When, Then: Then) {
        Given.iStartMyApp();
        <%_ startPages.forEach(function(pageName) { %>
        Then.onThe<%- pageName %>Generated.iSeeThisPage();
        <%_ }); -%>
    });

    <%_ if (!hideFilterBar && filterBarItems && filterBarItems.length > 0) { -%>
    opaTest("Check filter bar", function (_Given: Given, _When: When, Then: Then) {
        <%_ filterBarItems.forEach(function(item) { _%>
        <%_ if (item.custom) { _%>
        Then.onThe<%- startLR%>Generated.onFilterBar().iCheckFilterField("<%- item.description %>" as unknown as FilterFieldIdentifier);
        <%_ } else { _%>
        Then.onThe<%- startLR%>Generated.onFilterBar().iCheckFilterField({ property: "<%- item.property %>" });
        <%_ } _%>
        <%_ }); -%>
    });
<%_ } -%>
<%_ if (semanticKey && semanticKey.missingFromFilterBar && semanticKey.missingFromFilterBar.length > 0) { %>
    opaTest("Add semantic key properties to filter bar", function (_Given: Given, When: When, Then: Then) {
        When.onThe<%- startLR%>Generated.onFilterBar().iOpenFilterAdaptation();
        <%_ semanticKey.missingFromFilterBar.forEach(function(property) { _%>
        When.onThe<%- startLR%>Generated.onFilterBar().iAddAdaptationFilterField({ property: "<%- property %>" });
        <%_ }); -%>
        When.onThe<%- startLR%>Generated.onFilterBar().iConfirmFilterAdaptation();
        <%_ semanticKey.missingFromFilterBar.forEach(function(property) { _%>
        Then.onThe<%- startLR%>Generated.onFilterBar().iCheckFilterField({ property: "<%- property %>" });
        <%_ }); -%>
        <%_ semanticKey.missingFromFilterBar.forEach(function(property) { _%>
        // When.onThe<%- startLR%>Generated.onFilterBar().iChangeFilterField({ property: "<%- property %>" }, "<value to filter>", false);
        <%_ }); -%>
        // When.onThe<%- startLR%>Generated.onFilterBar().iExecuteSearch();
        // Then.onThe<%- startLR%>Generated.onTable(defaultTableId).iCheckRows();
        // When.onThe<%- startLR%>Generated.onTable(defaultTableId).iSelectRows(0);
        // Then.onThe<%- startLR%>Generated.onTable(defaultTableId).iCheckAction("<Action Name>", { enabled: true });
    });
<%_ } -%>

    // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
    // opaTest("Perform a global search and check the result", function (Given: Given, When: When, Then: Then) {
    //     When.onThe<%- startLR%>Generated.onFilterBar().iChangeSearchField("Search Term");
    //     When.onThe<%- startLR%>Generated.onFilterBar().iExecuteSearch();
    //     Then.onThe<%- startLR%>Generated.onTable(defaultTableId).iCheckRows();
    // });

<%_ if ((toolBarActions && toolBarActions.length > 0 ) || (tableColumns && Object.keys(tableColumns).length > 0)) { -%>
    opaTest("Check table columns and actions", function (_Given: Given, _When: When, Then: Then) {
        <%_ if (toolBarActions && toolBarActions.length > 0) { -%>
        <%_ if (createButton.visible && !isALP) { _%>
        Then.onThe<%- startLR%>Generated.onTable(defaultTableId).iCheckCreate({ visible: true });
        // When.onThe<%- startLR%>Generated.onTable(defaultTableId).iPressCreate();
        <%_ } _%>
        <%_ if (deleteButton.visible) { _%>
        // When.onThe<%- startLR%>Generated.onTable(defaultTableId).iPressDelete();
        Then.onThe<%- startLR%>Generated.onTable(defaultTableId).iCheckDelete({ visible: true });
        <%_ } _%>
        <%_ toolBarActions.forEach(function(item) { _%>
        <%_ if (item.visible) { _%>
        // When.onThe<%- startLR%>Generated.onTable(defaultTableId).iPressAction("<%- item.label %>");
        Then.onThe<%- startLR%>Generated.onTable(defaultTableId).iCheckAction("<%- item.label %>", { enabled: <%- item.enabled === true %> });
        <%_ } _%>
        <%_ }); -%>
        <%_ } -%>
        <%_ if (tableColumns && Object.keys(tableColumns).length > 0) { -%>
        Then.onThe<%- startLR %>Generated.onTable(defaultTableId).iCheckColumns(undefined, <%- JSON.stringify(tableColumns) %>);
        <%_ } -%>
    });
<%_ } -%>

<%_ if (startLR) { -%>
    opaTest("Navigate to ObjectPage", function (_Given: Given, When: When, Then: Then) {
        // Note: this test will fail if the ListReport page doesn't show any data
        <%_ if (!hideFilterBar) { -%>
        When.onThe<%- startLR%>Generated.onFilterBar().iExecuteSearch();
        <%_ } -%>
        <%_ if (tableIdentifiers && tableIdentifiers.length > 0) { -%>
        <%_ tableIdentifiers.forEach(function(tabId) { _%>
        When.onThe<%- startLR%>Generated.iGoToView({ key: "<%- tabId %>" });
        Then.onThe<%- startLR%>Generated.onTable("<%- tabId %>").iCheckRows();
        <%_ }); -%>
        <%_ } else { -%>
        Then.onThe<%- startLR%>Generated.onTable(defaultTableId).iCheckRows();
        <%_ } -%>
        <%_ if (navigatedOP) { -%>
        <%_ if (tableIdentifiers && tableIdentifiers.length > 0) { _%>
        When.onThe<%- startLR%>Generated.iGoToView({ key: defaultTableId });
        <%_ } _%>
        When.onThe<%- startLR%>Generated.onTable(defaultTableId).iPressRow(0);
        Then.onThe<%- navigatedOP%>Generated.iSeeThisPage();
        <%_ } -%>
    });
<%_ } -%>

    opaTest("Teardown", function (Given: Given) {
        // Cleanup
        Given.iTearDownMyApp();
    });
}

runner.run([journey]);
