export const FileName = {
    AdaptationConfig: 'config.json',
    CapJavaApplicationYaml: 'application.yaml',
    ExtConfigJson: '.extconfig.json',
    Library: '.library',
    Manifest: 'manifest.json',
    ManifestAppDescrVar: 'manifest.appdescr_variant',
    MtaYaml: 'mta.yaml',
    Package: 'package.json',
    Pom: 'pom.xml',
    Tsconfig: 'tsconfig.json',
    Ui5Yaml: 'ui5.yaml',
    Ui5LocalYaml: 'ui5-local.yaml',
    Ui5MockYaml: 'ui5-mock.yaml',
    UI5DeployYaml: 'ui5-deploy.yaml'
} as const;

export enum DirName {
    Changes = 'changes',
    Sapux = 'src',
    Schemas = '.schemas',
    Pages = 'pages',
    Webapp = 'webapp',
    Temp = '.tmp',
    LocalService = 'localService',
    Controller = 'controller',
    View = 'view',
    Fragment = 'fragment',
    Fragments = 'fragments',
    Ext = 'ext',
    VSCode = '.vscode',
    AppConfig = 'appconfig',
    Db = 'db',
    Csv = 'csv',
    Data = 'data',
    Mockdata = 'mockdata',
    Dist = 'dist',
    Coding = 'coding',
    Manifest = 'manifest',
    Annotations = 'annotations'
}
