export const API_BUSINESS_HUB_ENTERPRISE_PREFIX = 'ABHE';
export const DEFAULT_MTA_DESTINATION = 'fiori-default-srv-api';
export const DESTINATION_AUTHTYPE_NOTFOUND = 'NotAvailable';
export const DESTINATION_CHOICE_NONE = 'NONE';
export const DESTINATION_CHOICE_DIRECT_SERVICE_BINDING = 'DIRECT_SERVICE_BINDING';
