export { buildAst } from './ast';

export {
    EMPTY_VALUE_TYPE,
    RECORD_PROPERTY_TYPE,
    PATH_TYPE,
    STRING_LITERAL_TYPE,
    ANNOTATION_TYPE,
    RECORD_TYPE,
    ANNOTATION_GROUP_ITEMS_TYPE,
    ANNOTATION_GROUP_TYPE,
    BOOLEAN_TYPE,
    NUMBER_LITERAL_TYPE,
    ENUM_TYPE,
    COLLECTION_TYPE,
    TOKEN_TYPE,
    QUOTED_LITERAL_TYPE,
    QUALIFIER_TYPE,
    MULTI_LINE_STRING_LITERAL_TYPE,
    SEPARATOR_TYPE,
    IDENTIFIER_TYPE,
    OPERATOR_TYPE,
    UNSUPPORTED_OPERATOR_EXPRESSION_TYPE,
    INCORRECT_EXPRESSION_TYPE,
    CORRECT_EXPRESSION_TYPE,
    EXPRESSION_TYPES,
    FLATTENED_EXPRESSION_TYPE,
    FLATTENED_PATH_TYPE,
    FLATTENED_ANNOTATION_SEGMENT_TYPE,
    FLATTENED_PROPERTY_SEGMENT_TYPE,
    Expression,
    UnsupportedOperatorExpression,
    IncorrectExpression,
    CorrectExpression,
    Record,
    Node,
    AnnotationValue,
    AnnotationGroup,
    AnnotationNodeType,
    AnnotationGroupItems,
    Collection,
    Enum,
    StringLiteral,
    Path,
    EmptyValue,
    BooleanLiteral,
    NumberLiteral,
    QuotedLiteralKind,
    Token,
    QuotedLiteral,
    MultiLineStringLiteral,
    Identifier,
    Annotation,
    RecordProperty,
    AnnotationNode,
    Assignment,
    Separator,
    NarrowAnnotationNode,
    FlattenedExpression,
    FlattenedPath,
    FlattenedPathSegment,
    FlattenedAnnotationSegment,
    FlattenedPropertySegment,
    nodeRange,
    isContainer
} from './annotation-ast-nodes';

export { arePositionsEqual, copyPosition, copyRange, areRangesEqual } from './range';

export {
    operatorMap,
    positionIsInExpressionWhiteSpace,
    getEdmOperatorMap,
    containsIncorrectExpressions
} from './expressions';
