/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom pages:                                       ║ *
 * ║   - Create a new page file in this directory.                         ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the JourneyRunner.                            ║ *
 * ║   - Custom page files are not overwritten.                            ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

export const actions = {};

export const assertions = {};

export default class ListReport {
    actions = actions;
    assertions = assertions;
}
