/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("TravelObjectPageObjectPage journey");

        opaTest("Navigate to TravelObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheTravelList.onFilterBar().iExecuteSearch();

            Then.onTheTravelList.onTable().iCheckRows();
            When.onTheTravelList.onTable().iPressRow(0);

            Then.onTheTravelObjectPage.iSeeThisPage();
        });

        opaTest("Check header actions of the Object Page", function (Given, When, Then) {
            // Ensure the opened entity is not in Draft state before uncommenting
            // Then.onTheTravelObjectPage.onHeader().iCheckEdit({ visible: true });
            // When.onTheTravelObjectPage.onHeader().iPressEdit();
            Then.onTheTravelObjectPage.onHeader().iCheckAction("Set Cancel Date to Tomorrow" /* , { enabled: true } */);
            // When.onTheTravelObjectPage.onHeader().iPressAction("Set Cancel Date to Tomorrow");
            Then.onTheTravelObjectPage.onHeader().iCheckAction("Set To Booked" /* , { enabled: true } */);
            // When.onTheTravelObjectPage.onHeader().iPressAction("Set To Booked");
            Then.onTheTravelObjectPage.onHeader().iCheckAction("Set To New" /* , { enabled: true } */);
            // When.onTheTravelObjectPage.onHeader().iPressAction("Set To New");
            Then.onTheTravelObjectPage.onHeader().iCheckAction("Check Travel" /* , { enabled: true } */);
            // When.onTheTravelObjectPage.onHeader().iPressAction("Check Travel");
            Then.onTheTravelObjectPage.onHeader().iCheckAction("Deduct Discount" /* , { enabled: true } */);
            // When.onTheTravelObjectPage.onHeader().iPressAction("Deduct Discount");
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheTravelObjectPage.iCheckNumberOfSections(2);
            When.onTheTravelObjectPage.iPressSectionIconTabFilterButton("Travel");
            Then.onTheTravelObjectPage.iCheckSection({ section: "Travel" });
            Then.onTheTravelObjectPage.onForm({ section: "Travel" }).iCheckField({ property: "TravelID" });
            Then.onTheTravelObjectPage.onForm({ section: "Travel" }).iCheckField({ property: "AgencyID" });
            Then.onTheTravelObjectPage.onForm({ section: "Travel" }).iCheckField({ property: "CustomerID" });
            Then.onTheTravelObjectPage.onForm({ section: "Travel" }).iCheckField({ property: "BeginDate" });
            Then.onTheTravelObjectPage.onForm({ section: "Travel" }).iCheckField({ property: "EndDate" });
            Then.onTheTravelObjectPage.onForm({ section: "Travel" }).iCheckField({ property: "BookingFee" });
            Then.onTheTravelObjectPage.onForm({ section: "Travel" }).iCheckField({ property: "TotalPrice" });
            Then.onTheTravelObjectPage.onForm({ section: "Travel" }).iCheckField({ property: "LatestCancellationDate" });
            Then.onTheTravelObjectPage.onForm({ section: "Travel" }).iCheckField({ property: "Memo" });
            Then.onTheTravelObjectPage.onForm({ section: "Travel" }).iCheckField({ property: "Status" });
            When.onTheTravelObjectPage.iPressSectionIconTabFilterButton("Booking");
            Then.onTheTravelObjectPage.iCheckSection({ section: "Booking" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});