/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("TravelListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheTravelListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheTravelListGenerated.onFilterBar().iCheckFilterField("Travel ID");
            Then.onTheTravelListGenerated.onFilterBar().iCheckFilterField("Agency ID");
            Then.onTheTravelListGenerated.onFilterBar().iCheckFilterField("Customer ID");
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheTravelListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheTravelListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheTravelListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheTravelListGenerated.onTable().iCheckCreate({ visible: true });
            // Then.onTheTravelListGenerated.onTable().iPressCreate();
            // Then.onTheTravelListGenerated.onTable().iPressDelete();
            Then.onTheTravelListGenerated.onTable().iCheckDelete({ visible: true });
            // Then.onTheTravelListGenerated.onTable().iPressAction("Draft Template");
            Then.onTheTravelListGenerated.onTable().iCheckAction("Draft Template", { enabled: true });
            // Then.onTheTravelListGenerated.onTable().iPressAction("Active Template");
            Then.onTheTravelListGenerated.onTable().iCheckAction("Active Template", { enabled: true });
            // Then.onTheTravelListGenerated.onTable().iPressAction("Deduct Discount");
            Then.onTheTravelListGenerated.onTable().iCheckAction("Deduct Discount", { enabled: false });
            // Then.onTheTravelListGenerated.onTable().iPressAction("Check Travel");
            Then.onTheTravelListGenerated.onTable().iCheckAction("Check Travel", { enabled: false });
            // Then.onTheTravelListGenerated.onTable().iPressAction("Set To New");
            Then.onTheTravelListGenerated.onTable().iCheckAction("Set To New", { enabled: false });
            // Then.onTheTravelListGenerated.onTable().iPressAction("Set To Booked");
            Then.onTheTravelListGenerated.onTable().iCheckAction("Set To Booked", { enabled: false });
            // Then.onTheTravelListGenerated.onTable().iPressAction("Set Cancel Date to Tomorrow");
            Then.onTheTravelListGenerated.onTable().iCheckAction("Set Cancel Date to Tomorrow", { enabled: false });
            Then.onTheTravelListGenerated.onTable().iCheckColumns(undefined, {"TravelID":{"header":"Travel ID"},"AgencyID":{"header":"Agency ID"},"CustomerID":{"header":"Customer ID"},"BeginDate":{"header":"Starting Date"},"EndDate":{"header":"End Date"},"BookingFee":{"header":"Booking Fee"},"TotalPrice":{"header":"Total Price"},"LatestCancellationDate":{"header":"Latest Cancellation Date"},"Memo":{"header":"Description"},"Status":{"header":"Travel Status"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheTravelListGenerated.onFilterBar().iExecuteSearch();
            
            Then.onTheTravelListGenerated.onTable().iCheckRows();

            When.onTheTravelListGenerated.onTable().iPressRow(0);
            Then.onTheTravelObjectPageGenerated.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});