export enum EventName {
    Test = 'test',
    CPE_EVENT = 'CONTROL_PROPERTY_EDITOR_EVENT',
    ADP_EVENT = 'ADAPTATION_PROJECT_EVENT',
    TELEMETRY_SETTINGS_INIT_FAILED = 'TELEMETRY_SETTINGS_INIT_FAILED',
    DISABLE_TELEMETRY = 'DISABLE_TELEMETRY'
}
