/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("SalesOrderItemListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheSalesOrderItemListGenerated.iSeeThisPage();
        });


        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onTheSalesOrderItemListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onTheSalesOrderItemListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onTheSalesOrderItemListGenerated.onTable().iCheckRows();
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            // When.onTheSalesOrderItemListGenerated.onTable().iPressDelete();
            Then.onTheSalesOrderItemListGenerated.onTable().iCheckDelete({ visible: true });
            // When.onTheSalesOrderItemListGenerated.onTable().iPressAction({ service: "com.c_salesordermanage_sd_aggregate", action: "c_salesordermanage_sd_aggregate/ReturnInProcess", unbound: true });
            Then.onTheSalesOrderItemListGenerated.onTable().iCheckAction({ service: "com.c_salesordermanage_sd_aggregate", action: "c_salesordermanage_sd_aggregate/ReturnInProcess", unbound: true }, { enabled: true });
            // When.onTheSalesOrderItemListGenerated.onTable().iPressAction({ service: "com.c_salesordermanage_sd_aggregate", action: "DummyBoundAction", unbound: false });
            Then.onTheSalesOrderItemListGenerated.onTable().iCheckAction({ service: "com.c_salesordermanage_sd_aggregate", action: "DummyBoundAction", unbound: false }, { enabled: false });
            Then.onTheSalesOrderItemListGenerated.onTable().iCheckColumns(undefined, {"10":{"header":"Bound Action"},"11":{"header":"IBN"},"SalesOrderItem":{"header":"Item"},"HigherLevelItem":{"header":"Higher-Level Item"},"Material":{"header":"Material"},"RequestedQuantity":{"header":"Requested Quantity"},"SalesOrderItemCategory":{"header":"Item Category"},"RequestedDeliveryDate":{"header":"Delivery Date"},"NetAmount":{"header":"Net Value"},"_Material/Material":{"header":"Material"},"isVerified":{"header":"Verified Material"},"_ReferencedSalesOrder/SalesOrder":{"header":"Referenced Sales Order"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onTheSalesOrderItemListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheSalesOrderItemListGenerated.onTable().iCheckRows();
            When.onTheSalesOrderItemListGenerated.onTable().iPressRow(0);
            Then.onTheSalesOrderItemObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});