/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("SalesOrderItemObjectPageObjectPage journey");

        opaTest("Navigate to SalesOrderItemObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheSalesOrderItemList.onFilterBar().iExecuteSearch();

            Then.onTheSalesOrderItemList.onTable().iCheckRows();
            When.onTheSalesOrderItemList.onTable().iPressRow(0);

            Then.onTheSalesOrderItemObjectPage.iSeeThisPage();
        });

        opaTest("Check header actions of the Object Page", function (Given, When, Then) {
            // Ensure the opened entity is not in Draft state before uncommenting
            // Then.onTheSalesOrderItemObjectPage.onHeader().iCheckEdit({ visible: true });
            // When.onTheSalesOrderItemObjectPage.onHeader().iPressEdit();
            Then.onTheSalesOrderItemObjectPage.onHeader().iCheckAction("Identification Form Action" /* , { enabled: true } */);
            // When.onTheSalesOrderItemObjectPage.onHeader().iPressAction("Identification Form Action");
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheSalesOrderItemObjectPage.iCheckNumberOfSections(2);
            When.onTheSalesOrderItemObjectPage.iPressSectionIconTabFilterButton("Identification");
            Then.onTheSalesOrderItemObjectPage.iCheckSection({ section: "Identification" });
            Then.onTheSalesOrderItemObjectPage.onForm({ section: "Identification" }).iCheckField({ property: "_ReferencedSalesOrder/SalesOrder" });
            Then.onTheSalesOrderItemObjectPage.onForm({ section: "Identification" }).iCheckField({ property: "SalesOrderItem" });
            Then.onTheSalesOrderItemObjectPage.onForm({ section: "Identification" }).iCheckField({ property: "Material" });
            Then.onTheSalesOrderItemObjectPage.onForm({ section: "Identification" }).iCheckField({ property: "RequestedQuantity" });
            Then.onTheSalesOrderItemObjectPage.onForm({ section: "Identification" }).iCheckField({ property: "NetAmount" });
            Then.onTheSalesOrderItemObjectPage.onForm({ section: "Identification" }).iCheckField({ property: "_ReferencedSalesOrderItem/SalesOrderItem" });
            When.onTheSalesOrderItemObjectPage.iPressSectionIconTabFilterButton("MaterialDetailsFacet");
            Then.onTheSalesOrderItemObjectPage.iCheckSection({ section: "MaterialDetailsFacet" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});