/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("SalesOrderItemObjectPageObjectPage journey");

        opaTest("Navigate to SalesOrderItemObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheSalesOrderItemListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheSalesOrderItemListGenerated.onTable().iCheckRows();
            When.onTheSalesOrderItemListGenerated.onTable().iPressRow(0);

            Then.onTheSalesOrderItemObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Check header actions of the Object Page", function (Given, When, Then) {
            // Ensure the opened entity is not in Draft state before uncommenting
            // Then.onTheSalesOrderItemObjectPageGenerated.onHeader().iCheckEdit({ visible: true });
            // When.onTheSalesOrderItemObjectPageGenerated.onHeader().iExecuteEdit();
            Then.onTheSalesOrderItemObjectPageGenerated.onHeader().iCheckAction({ service: "com.c_salesordermanage_sd_aggregate", action: "IdentificationFormAction", unbound: false } /* , { enabled: true } */);
            // When.onTheSalesOrderItemObjectPageGenerated.onHeader().iPressAction({ service: "com.c_salesordermanage_sd_aggregate", action: "IdentificationFormAction", unbound: false });
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheSalesOrderItemObjectPageGenerated.iCheckNumberOfSections(2);
            When.onTheSalesOrderItemObjectPageGenerated.iGoToSection({ section: "Identification" });
            Then.onTheSalesOrderItemObjectPageGenerated.iCheckSection({ section: "Identification" });
            Then.onTheSalesOrderItemObjectPageGenerated.onForm({ section: "Identification" }).iCheckField({ property: "_ReferencedSalesOrder/SalesOrder" });
            Then.onTheSalesOrderItemObjectPageGenerated.onForm({ section: "Identification" }).iCheckField({ property: "SalesOrderItem" });
            Then.onTheSalesOrderItemObjectPageGenerated.onForm({ section: "Identification" }).iCheckField({ property: "Material" });
            Then.onTheSalesOrderItemObjectPageGenerated.onForm({ section: "Identification" }).iCheckField({ property: "RequestedQuantity" });
            Then.onTheSalesOrderItemObjectPageGenerated.onForm({ section: "Identification" }).iCheckField({ property: "NetAmount" });
            Then.onTheSalesOrderItemObjectPageGenerated.onForm({ section: "Identification" }).iCheckField({ property: "_ReferencedSalesOrderItem/SalesOrderItem" });
            When.onTheSalesOrderItemObjectPageGenerated.iGoToSection({ section: "MaterialDetailsFacet" });
            Then.onTheSalesOrderItemObjectPageGenerated.iCheckSection({ section: "MaterialDetailsFacet" });
            Then.onTheSalesOrderItemObjectPageGenerated.onTable({ property: "_MaterialDetails" }).iCheckAction({ service: "com.c_salesordermanage_sd_aggregate", action: "MaterialDetailsBoundAction", unbound: true }, { enabled: true });
            // When.onTheSalesOrderItemObjectPageGenerated.onTable({ property: "_MaterialDetails" }).iPressAction({ service: "com.c_salesordermanage_sd_aggregate", action: "MaterialDetailsBoundAction", unbound: true });
            Then.onTheSalesOrderItemObjectPageGenerated.onTable({ property: "_MaterialDetails" }).iCheckColumns(undefined, {"ModelYear":{"header":"Model Year"},"WarrantyYear":{"header":"Warranty Expiration"},"BrandCategory":{"header":"Material Category"},"FabricationCountry":{"header":"Fabrication Country"}});
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});
