name: REUSE Compliance Check

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    reuse-lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: REUSE Compliance Check
              uses: fsfe/reuse-action@v1
